name: q_play
description: "A professional sports turf booking application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  # Core
  provider: ^6.1.2
  shared_preferences: ^2.4.0
  http: ^1.2.2
  dio: ^5.9.2
  image_picker: ^1.1.2
  intl: ^0.20.2

  # Features
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  share_plus: ^12.0.1
  pdf: ^3.11.1
  printing: ^5.13.3
  flutter_native_splash: ^2.4.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Navigation & DI
  go_router: ^17.0.1
  get_it: ^9.2.1

  # JSON
  json_annotation: ^4.11.0

  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # UI
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.1
  csc_picker: ^0.2.7
  firebase_core: ^4.6.0
  firebase_messaging: ^16.1.3
  flutter_local_notifications: ^21.0.0
  syncfusion_flutter_xlsio: ^33.2.12
dev_dependencies:
  flutter_test:
    sdk: flutter

  sqflite: ^2.4.1
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.11
  json_serializable: ^6.13.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/no-turf-image.png
    - assets/sql/init_db.sql

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true